; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Created with BEEhive - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   BEEhive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


spriteanims_djakk:

spriteanim_djakk_idle:
spriteanim_djakk_idle_numframes: equ 0x1
spriteanim_djakk_idle_speed: equ 0x1
spriteanim_djakk_idle_track_frames:
	dc.b 0x0
spriteanim_djakk_idle_track_posx:

spriteanim_djakk_idle_track_posy:


	Even

spriteanim_djakk_roar:
spriteanim_djakk_roar_numframes: equ 0x7
spriteanim_djakk_roar_speed: equ 0x20
spriteanim_djakk_roar_track_frames:
	dc.b 0x0, 0x1, 0x2, 0x2, 0x2, 0x1, 0x0
spriteanim_djakk_roar_track_posx:

spriteanim_djakk_roar_track_posy:


	Even

spriteanim_djakk_run:
spriteanim_djakk_run_numframes: equ 0x8
spriteanim_djakk_run_speed: equ 0x28
spriteanim_djakk_run_track_frames:
	dc.b 0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7
spriteanim_djakk_run_track_posx:

spriteanim_djakk_run_track_posy:


	Even

spriteanim_djakk_emerge:
spriteanim_djakk_emerge_numframes: equ 0x1
spriteanim_djakk_emerge_speed: equ 0x1
spriteanim_djakk_emerge_track_frames:
	dc.b 0x0
spriteanim_djakk_emerge_track_posx:

spriteanim_djakk_emerge_track_posy:


	Even

spriteanim_djakk_bite:
spriteanim_djakk_bite_numframes: equ 0x5
spriteanim_djakk_bite_speed: equ 0x2F
spriteanim_djakk_bite_track_frames:
	dc.b 0x0, 0x1, 0x2, 0x3, 0x4
spriteanim_djakk_bite_track_posx:

spriteanim_djakk_bite_track_posy:


	Even

spriteanim_djakk_death:
spriteanim_djakk_death_numframes: equ 0x1
spriteanim_djakk_death_speed: equ 0x1
spriteanim_djakk_death_track_frames:
	dc.b 0x0
spriteanim_djakk_death_track_posx:

spriteanim_djakk_death_track_posy:


	Even

spriteanim_djakk_walk:
spriteanim_djakk_walk_numframes: equ 0x8
spriteanim_djakk_walk_speed: equ 0x14
spriteanim_djakk_walk_track_frames:
	dc.b 0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7
spriteanim_djakk_walk_track_posx:

spriteanim_djakk_walk_track_posy:


	Even

