; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Created with BEEhive - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   BEEhive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


spriteanims_djrake:

spriteanim_djrake_idle:
spriteanim_djrake_idle_numframes: equ 0x1
spriteanim_djrake_idle_speed: equ 0x1
spriteanim_djrake_idle_track_frames:
	dc.b 0x0
	Even
spriteanim_djrake_idle_track_posx:

	Even
spriteanim_djrake_idle_track_posy:

	Even
spriteanim_djrake_idle_track_sfx:
	Even

