; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Created with BEEhive - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   BEEhive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


spriteanims_flueleaf:

spriteanim_flueleaf_flueleaf:
spriteanim_flueleaf_flueleaf_numframes: equ 0x9
spriteanim_flueleaf_flueleaf_speed: equ 0x3C
spriteanim_flueleaf_flueleaf_track_frames:
	dc.b 0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8
spriteanim_flueleaf_flueleaf_track_posx:

spriteanim_flueleaf_flueleaf_track_posy:


	Even

