; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   **AUTOGENERATED WITH BEEHIVE** - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Beehive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


tiles_L7_size_b	equ 0x00009A00	; Size in bytes
tiles_L7_size_w	equ (tiles_L7_size_b/2)	; Size in words
tiles_L7_size_l	equ (tiles_L7_size_b/4)	; Size in longwords
tiles_L7_size_t	equ 1232	; Size in tiles
