; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   **AUTOGENERATED WITH BEEHIVE** - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Beehive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


tiles_L3_size_b	equ 0x00004080	; Size in bytes
tiles_L3_size_w	equ (tiles_L3_size_b/2)	; Size in words
tiles_L3_size_l	equ (tiles_L3_size_b/4)	; Size in longwords
tiles_L3_size_t	equ 516	; Size in tiles
