; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Created with BEEhive - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   BEEhive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


map_blockmap_twd_logo_size_b	equ 0x000000A0	; Size in bytes
map_blockmap_twd_logo_size_w	equ (map_blockmap_twd_logo_size_b/2)	; Size in words
map_blockmap_twd_logo_size_l	equ (map_blockmap_twd_logo_size_b/4)	; Size in longwords
map_twd_logo_width	equ 0x28
map_twd_logo_height	equ 0x20
map_blockmap_twd_logo_width	equ 0x0A
map_blockmap_twd_logo_height	equ 0x08
