; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Created with BEEhive - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   BEEhive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


map_blockmap_L1BG_size_b	equ 0x00000100	; Size in bytes
map_blockmap_L1BG_size_w	equ (map_blockmap_L1BG_size_b/2)	; Size in words
map_blockmap_L1BG_size_l	equ (map_blockmap_L1BG_size_b/4)	; Size in longwords
map_L1BG_width	equ 0x40
map_L1BG_height	equ 0x20
map_blockmap_L1BG_width	equ 0x10
map_blockmap_L1BG_height	equ 0x08
