; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   **AUTOGENERATED WITH BEEHIVE** - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Beehive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


map_blocks_tst1_size_b	equ 0x000000E0	; Size in bytes
map_blocks_tst1_size_w	equ (map_blocks_tst1_size_b/2)	; Size in words
map_blocks_tst1_size_l	equ (map_blocks_tst1_size_b/4)	; Size in longwords
map_blocks_tst1_num_blocks	equ 7	; Size in blocks
