; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   **AUTOGENERATED WITH BEEHIVE** - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Beehive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


map_blockmap_tst1_size_b	equ 0x00000100	; Size in bytes
map_blockmap_tst1_size_w	equ (map_blockmap_tst1_size_b/2)	; Size in words
map_blockmap_tst1_size_l	equ (map_blockmap_tst1_size_b/4)	; Size in longwords
map_tst1_width	equ 0x80
map_tst1_height	equ 0x40
map_blockmap_tst1_width	equ 0x20
map_blockmap_tst1_height	equ 0x10

map_blockmap_tst1_coloffsets:
	dc.w 0x0000
	dc.w 0x0008
	dc.w 0x0010
	dc.w 0x0018
	dc.w 0x0020
	dc.w 0x0028
	dc.w 0x0030
	dc.w 0x0038
	dc.w 0x0040
	dc.w 0x0048
	dc.w 0x0050
	dc.w 0x0058
	dc.w 0x0060
	dc.w 0x0068
	dc.w 0x0070
	dc.w 0x0078
	dc.w 0x0080
	dc.w 0x0088
	dc.w 0x0090
	dc.w 0x0098
	dc.w 0x00A0
	dc.w 0x00A8
	dc.w 0x00B0
	dc.w 0x00B8
	dc.w 0x00C0
	dc.w 0x00C8
	dc.w 0x00D0
	dc.w 0x00D8
	dc.w 0x00E0
	dc.w 0x00E8
	dc.w 0x00F0
	dc.w 0x00F8
