; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   **AUTOGENERATED WITH BEEHIVE** - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Beehive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


terrainmap_blocks_tst1_size_b	equ 0x000000C0	; Size in bytes
terrainmap_blocks_tst1_size_w	equ (terrainmap_blocks_tst1_size_b/2)	; Size in words
terrainmap_blocks_tst1_size_l	equ (terrainmap_blocks_tst1_size_b/4)	; Size in longwords
terrainmap_blocks_tst1_num_blocks	equ 6	; Size in blocks
