; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   **AUTOGENERATED WITH BEEHIVE** - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Beehive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


TerrainTiles_tst1_size_b	equ 0x00000010	; Size in bytes
TerrainTiles_tst1_size_w	equ (TerrainTiles_tst1_size_b/2)	; Size in words
TerrainTiles_tst1_size_l	equ (TerrainTiles_tst1_size_b/4)	; Size in longwords
TerrainTiles_tst1_size_t	equ 2	; Size in tiles
