; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   **AUTOGENERATED WITH BEEHIVE** - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Beehive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


tst1_Leaf_count equ 0x0

tst1_Trap_count equ 0x0

tst1_Djubb_count equ 0x0

tst1_Echo_count equ 0x0

tst1_Nymn_count equ 0x1
tst1_Nymn_1_idx	equ 0x0

	IFND FINAL
tst1_Nymn_1_name	dc.b "tst1_Nymn_1",0
	even
	ENDIF

tst1_BouncePlant_count equ 0x0

tst1_Borgus_count equ 0x0

tst1_DjakkCage_count equ 0x0

tst1_Log_count equ 0x0

tst1_Monster_count equ 0x0

tst1_Boulder_count equ 0x0

tst1_Firefly_count equ 0x0

tst1_FuzzlCage_count equ 0x0

tst1_Fuzzl_count equ 0x0

tst1_Stone_count equ 0x0

tst1_Demon_count equ 0x0

tst1_Raft_count equ 0x0

tst1_Nest_count equ 0x0

tst1_Flue_count equ 0x0

tst1_TriggerBox_count equ 0x0

tst1_Checkpoint_count equ 0x0

tst1_WaterBody_count equ 0x0

tst1_Location_count equ 0x0

tst1_Deathbox_count equ 0x0

tst1_Lift_count equ 0x0

tst1_Crate_count equ 0x0

tst1_Generator_count equ 0x0

tst1_Cogs_count equ 0x0

tst1_Button_count equ 0x0

tst1_Wyrm_count equ 0x0

tst1_AIMarker_count equ 0x0

tst1_Cart_count equ 0x0

tst1_Winch_count equ 0x0

tst1_Pillar_count equ 0x0

tst1_WindFlue_count equ 0x0

tst1_Lock_count equ 0x0

tst1_Pool_count equ 0x0

tst1_Stalactite_count equ 0x0

tst1_CargoLift_count equ 0x0

tst1_Scrap_count equ 0x0

tst1_Longboat_count equ 0x0

tst1_Skivv_count equ 0x0

tst1_Ladder_count equ 0x0

tst1_Scirus_count equ 0x0

tst1_Hogg_count equ 0x0

tst1_Bridge_count equ 0x0

tst1_Swarm_count equ 0x0



tst1_LoadGameObjects:




	PUSHL  a1
	RAMPOOL_ALLOC Pool_Entities, #(Nymn_Struct_Size*tst1_Nymn_count)
	move.l a1, EntityPoolStart_Nymn
	move.l a1, a0
	POPL   a1

	jsr NymnInit
	move.l #0x01780000, Entity_WorldPosX(a0)
	move.l #0x02280000, Entity_WorldPosY(a0)
	jsr NymnLoadGfx
	IFND FINAL
	lea tst1_Nymn_1_name, a3
	move.l a0, a2
	add.l #Entity_DebugName, a2
	move.l #0xb, d0
	MEMCPYB a2,a3,d0
	ENDIF
	add.l #Nymn_Struct_Size, a0












































	rts

