; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   **AUTOGENERATED WITH BEEHIVE** - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Beehive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


tiles_tst1_size_b	equ 0x00000500	; Size in bytes
tiles_tst1_size_w	equ (tiles_tst1_size_b/2)	; Size in words
tiles_tst1_size_l	equ (tiles_tst1_size_b/4)	; Size in longwords
tiles_tst1_size_t	equ 40	; Size in tiles
