; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   **AUTOGENERATED WITH BEEHIVE** - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Beehive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


tiles_L1_size_b	equ 0x00008060	; Size in bytes
tiles_L1_size_w	equ (tiles_L1_size_b/2)	; Size in words
tiles_L1_size_l	equ (tiles_L1_size_b/4)	; Size in longwords
tiles_L1_size_t	equ 1027	; Size in tiles
