; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   **AUTOGENERATED WITH BEEHIVE** - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Beehive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


tiles_L6_size_b	equ 0x000075A0	; Size in bytes
tiles_L6_size_w	equ (tiles_L6_size_b/2)	; Size in words
tiles_L6_size_l	equ (tiles_L6_size_b/4)	; Size in longwords
tiles_L6_size_t	equ 941	; Size in tiles
