; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Created with BEEhive - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   BEEhive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


palette_boulder:
	dc.w	0x0C66
	dc.w	0x0004
	dc.w	0x0226
	dc.w	0x0040
	dc.w	0x0446
	dc.w	0x0262
	dc.w	0x0662
	dc.w	0x004A
	dc.w	0x0468
	dc.w	0x0882
	dc.w	0x006C
	dc.w	0x0202
	dc.w	0x04A0
	dc.w	0x0AC2
	dc.w	0x06AE
	dc.w	0x02EC

