
Pal_Nymn_Blue:
	dc.w	$300
	dc.w	$000
	dc.w	$500
	dc.w	$f00
	dc.w	$333
	dc.w	$fa0
	dc.w	$555
	dc.w	$faa
	dc.w	$aac
	dc.w	$fff
	dc.w	$5f5
	dc.w	$ff5
	dc.w	$55f
	dc.w	$f5f
	dc.w	$5ff
	dc.w	$fff
	
Pal_Nymn_Red:
	dc.w	$300
	dc.w	$000
	dc.w	$005
	dc.w	$00a
	dc.w	$333
	dc.w	$33c
	dc.w	$555
	dc.w	$faa
	dc.w	$aac
	dc.w	$fff
	dc.w	$5f5
	dc.w	$ff5
	dc.w	$55f
	dc.w	$f5f
	dc.w	$5ff
	dc.w	$fff

Pal_Nymn_Green:
	dc.w	$300
	dc.w	$000
	dc.w	$030
	dc.w	$0a0
	dc.w	$333
	dc.w	$0f0
	dc.w	$555
	dc.w	$faa
	dc.w	$aac
	dc.w	$fff
	dc.w	$5f5
	dc.w	$ff5
	dc.w	$55f
	dc.w	$f5f
	dc.w	$5ff
	dc.w	$fff
	
Pal_Nymn_Yellow:
	dc.w	$300
	dc.w	$000
	dc.w	$07f
	dc.w	$0ff
	dc.w	$333
	dc.w	$cff
	dc.w	$555
	dc.w	$faa
	dc.w	$aac
	dc.w	$fff
	dc.w	$5f5
	dc.w	$ff5
	dc.w	$55f
	dc.w	$f5f
	dc.w	$5ff
	dc.w	$fff

Pal_Nymn_White:
	dc.w	0x0200
	dc.w	0x0000
	dc.w	0x0AAA
	dc.w	0x0EEE
	dc.w	0x0222
	dc.w	0x0CCC
	dc.w	0x0888
	dc.w	0x0EAA
	dc.w	0x0AAC
	dc.w	0x0EEE
	dc.w	0x0000
	dc.w	0x0000
	dc.w	0x0000
	dc.w	0x0000
	dc.w	0x0000
	dc.w	0x0000