; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   **AUTOGENERATED WITH BEEHIVE** - the complete art tool for SEGA Mega Drive
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   http://www.bigevilcorporation.co.uk
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
;   Beehive and SEGA Genesis Framework (c) Matt Phillips 2015
; == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==


TerrainTiles_L4_size_b	equ 0x00000560	; Size in bytes
TerrainTiles_L4_size_w	equ (TerrainTiles_L4_size_b/2)	; Size in words
TerrainTiles_L4_size_l	equ (TerrainTiles_L4_size_b/4)	; Size in longwords
TerrainTiles_L4_size_t	equ 172	; Size in tiles
